-- V1__cria_esquema_inicial.sql
-- Esquema inicial do Feira Viva — gerado a partir do Hibernate DDL (Aula 07-12)

-- Tabela de categorias (Composite: autorelacionamento)
CREATE TABLE categorias (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(80) NOT NULL,
                            descricao VARCHAR(255),
                            categoria_pai_id BIGINT,
                            CONSTRAINT fk_categoria_pai FOREIGN KEY (categoria_pai_id) REFERENCES categorias(id)
);

-- Tabela de produtos
CREATE TABLE produtos (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR(120) NOT NULL,
                          descricao VARCHAR(500),
                          preco DECIMAL(10,2) NOT NULL,
                          sku VARCHAR(30) NOT NULL UNIQUE,
                          estoque INT NOT NULL DEFAULT 0,
                          ativo BOOLEAN NOT NULL DEFAULT TRUE,
                          url_imagem VARCHAR(500),
                          categoria_id BIGINT,
                          CONSTRAINT fk_produto_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id)
);
CREATE INDEX idx_produto_categoria ON produtos(categoria_id);

-- Tabela de clientes
CREATE TABLE clientes (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR(120) NOT NULL,
                          email VARCHAR(120) NOT NULL UNIQUE,
                          senha_hash VARCHAR(255) NOT NULL,
                          telefone VARCHAR(30),
                          papel VARCHAR(20) NOT NULL DEFAULT 'CLIENTE'
);
CREATE INDEX idx_cliente_email ON clientes(email);

-- Tabela de endereços
CREATE TABLE enderecos (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           cep VARCHAR(9) NOT NULL,
                           logradouro VARCHAR(120) NOT NULL,
                           numero VARCHAR(20) NOT NULL,
                           complemento VARCHAR(120),
                           bairro VARCHAR(80) NOT NULL,
                           cidade VARCHAR(80) NOT NULL,
                           uf VARCHAR(2) NOT NULL,
                           cliente_id BIGINT NOT NULL,
                           CONSTRAINT fk_endereco_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);
CREATE INDEX idx_endereco_cliente ON enderecos(cliente_id);

-- Tabela de carrinhos (1:1 com cliente)
CREATE TABLE carrinhos (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           cliente_id BIGINT NOT NULL UNIQUE,
                           data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           codigo_cupom VARCHAR(20),
                           estrategia_frete VARCHAR(20),
                           CONSTRAINT fk_carrinho_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

-- Tabela de itens de carrinho
CREATE TABLE itens_carrinho (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                carrinho_id BIGINT NOT NULL,
                                produto_id BIGINT NOT NULL,
                                quantidade INT NOT NULL,
                                preco_unitario DECIMAL(10,2) NOT NULL,
                                CONSTRAINT fk_itemcarr_carrinho FOREIGN KEY (carrinho_id) REFERENCES carrinhos(id) ON DELETE CASCADE,
                                CONSTRAINT fk_itemcarr_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);

-- Tabela de pedidos
CREATE TABLE pedidos (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         numero VARCHAR(20) UNIQUE,
                         cliente_id BIGINT NOT NULL,
                         endereco_id BIGINT NOT NULL,
                         status VARCHAR(20) NOT NULL,
                         subtotal DECIMAL(10,2) NOT NULL,
                         frete DECIMAL(10,2) NOT NULL,
                         total DECIMAL(10,2) NOT NULL,
                         data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
                         CONSTRAINT fk_pedido_endereco FOREIGN KEY (endereco_id) REFERENCES enderecos(id)
);
CREATE INDEX idx_pedido_cliente ON pedidos(cliente_id);
CREATE INDEX idx_pedido_status ON pedidos(status);

-- Tabela de itens de pedido (snapshot de preço)
CREATE TABLE itens_pedido (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              pedido_id BIGINT NOT NULL,
                              produto_id BIGINT NOT NULL,
                              quantidade INT NOT NULL,
                              preco_unitario DECIMAL(10,2) NOT NULL,
                              CONSTRAINT fk_itemped_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
                              CONSTRAINT fk_itemped_produto FOREIGN KEY (produto_id) REFERENCES produtos(id)
);